version: '3.4'

services:
  dockerfrontendbackenddb:
    image: dockerfrontendbackenddb
    build:
      context: api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
